package com.cruddynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.cruddynamodb.enums.GenderEnum;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

/**
 * Person model
 *
 * @author Lucas Araújo - lucas.compufc@gmail.com
 * @version 0.1
 * @since 24/02/21
 */
@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "Person")
public class Person {

    @Id
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "first_name")
    private String firstName;

    @DynamoDBAttribute(attributeName = "last_name")
    private String lastName;

    @DynamoDBAttribute(attributeName = "age")
    private Integer age;

    @DynamoDBAttribute(attributeName = "document_number")
    private String documentNumber;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "gender")
    private GenderEnum gender;
}
